openapi: 3.0.1
info:
  title: PizzaShack
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /menu:
    get:
      description: |
        Return a list of available menu items.
      parameters: []
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
